name: DesignguideTV
favicon: null
layout_spectrum: 0.6183
typography_spectrum: 0.3323
title: Designguide TV
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2167868-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16010a'
    - '#fe2e00'
    - '#fcb694'
    - '#5dfe96'
    - '#1badff'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
