name: DesignguideTV
favicon: null
layout_spectrum: 0.6323303941171616
typography_spectrum: 0.5207355879247189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.31910117738880217
  lightness: 0.9096013738308102
  saturation: 0.0576347503811121
  rhythmicContrast: 0.37131826276890934
purpose: []
