name: DesignguideTV
favicon: null
layout_spectrum: 0.79252
typography_spectrum: 0.6559139
title: The eternal wanderlust of design.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9dbd6'
    - '#35449f'
    - '#3f2723'
    - '#946b59'
    - '#738caa'
  brandStrength: 0.375
  lightness: 0.4444444
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
