name: DesignguideTV
favicon: null
layout_spectrum: 0.5609319
typography_spectrum: 0.6559139
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The eternal wanderlust of design.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060807'
    - '#37823a'
    - '#a67161'
    - '#3c241e'
    - '#363d69'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
