name: DesignguideTV
favicon: null
layout_spectrum: 0.65486
typography_spectrum: 0.51837
title: The eternal wanderlust of design.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aeb9bf'
    - '#342e2f'
    - '#0c0a0b'
    - '#686065'
    - '#91867c'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
